// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gleznmxmbkjlgdoannkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZXpubXhtYmtqbGdkb2FubmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTE2NjQsImV4cCI6MjA2NzQyNzY2NH0.a9FI3kRDjO1d-QwEyCtdcfptumGaZVWsEM95zRhOSEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});